---
- name: Install QEMU/KVM packages
  ansible.builtin.import_tasks: install.yml

- name: Configure systemd service for QEMU VMs
  ansible.builtin.import_tasks: systemd.yml

- name: Apply SELinux policy for QEMU VM service
  ansible.builtin.import_tasks: selinux.yml

- name: Install and run the labview console service
  ansible.builtin.import_tasks: labview.yml
  when: host_labview_enabled | bool
