---
- name: Install noVNC package
  ansible.builtin.dnf:
    name: novnc
    state: present
  become: true

- name: Install noVNC systemd template unit
  ansible.builtin.template:
    src: novnc@.service.j2
    dest: /etc/systemd/system/novnc@.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload systemd
