---
- name: Install edk2-ovmf
  ansible.builtin.dnf:
    name: edk2-ovmf
    state: present
  when: _vms_active_vms | selectattr('uefi', 'defined') | selectattr('uefi') | list | length > 0
        or (_vms_active_vms | rejectattr('uefi', 'defined') | list | length > 0 and vms_default_uefi)

- name: Copy OVMF_VARS per-VM
  ansible.builtin.copy:
    src: "{{ vms_ovmf_vars_template }}"
    dest: "{{ vms_image_dir }}/{{ item.name }}_VARS.fd"
    remote_src: true
    force: false
    owner: "{{ vms_service_user }}"
    group: "{{ vms_service_group }}"
    mode: "0644"
  loop: "{{ _vms_active_vms | selectattr('uefi', 'defined') | selectattr('uefi') | list
            + (_vms_active_vms | rejectattr('uefi', 'defined') | list if vms_default_uefi else []) }}"
  loop_control:
    label: "{{ item.name }}"
